general:
  do_safety_checks: true

data:
  default_dataset_paths: ["analyzer_resources/datasets"]
  default_era_paths: ["analyzer_resources/eras"]
  cache_location: ".analyzer_data/caches"
  use_compression: true
  compression_lib: lz4





  
